### ISSUE TITLE
在PowerShell中运行ssr_dup_remover.py时，出现SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by DawnDu** [Justsoos/ss-ssr-gadget#1]
![default](https://user-images.githubusercontent.com/33946525/43673575-f5a4f1ae-97f7-11e8-8823-2715c25dc993.PNG)

**Comment by Justsoos** [comment]
请用文本编辑器，打开你下载 的 `ssr_dup_remover.py `文件，核实确定是正确的内容。

**Comment by DawnDu** [comment]
问题已解决，非常感谢！
出错的原因是直接在ssr_dup_remover.py文件名上“右键->使用IDM下载”，下载下来的似乎是html，但是文件名和扩展名被IDM自动重命名为ssr_dup_remover.py，导致小白（我）以为下载下来的是正确文件，经@Justsoos提醒，才发现错误。
非常感谢！
