### ISSUE TITLE
运行"check_v2ray.py"出现了问题，麻烦大佬看一下这是什么情况？

### ISSUE THREAD

**Issue by DawnDu** [Justsoos/ss-ssr-gadget#2]
![1_0](https://user-images.githubusercontent.com/33946525/43703793-7890f362-9990-11e8-862e-513a0dabfcfc.PNG)

生成了一些`temp…….json`文件
![1_1](https://user-images.githubusercontent.com/33946525/43703794-78cfcc86-9990-11e8-9ff5-86b05ab13daf.PNG)

请问大佬，该如何做才能解决这个问题呢？

**Comment by Justsoos** [comment]
运行目录下必须存在 v2ray.exe wv2ray.exe 等相关程序，并且防火墙配置其可连接 Internet。
正常运行 python 脚本情况下 temp 文件会自动被删除。
脚本运行出错可以手动删除 temp 文件，不会造成任何影响。

**Comment by DawnDu** [comment]
@Justsoos 运行目录下已存在 v2ray.exe wv2ray.exe 等相关程序，且防火墙已配置其可连接 Internet。
`check_v2ray.py`在运行时只能执行一半的操作，即能够发现有几个重复的服务器，根据提示按`enter`键继续执行时，则会出现：
`multiprocessing.pool.RemoteTraceback:`
`"""`
`Traceback (most recent call last)`
……
`FileNotFoundError: [Errno 2] No such file or directory: ……`
具体细节如下图（和之前的图片显示的一样），请问是不是我这边的防火墙设置仍然不正确？
![2](https://user-images.githubusercontent.com/33946525/44374024-c820e100-a51e-11e8-9917-3c655cc154c5.PNG)

**Comment by Justsoos** [comment]
目前脚本不支持 Linux on Win10 （WSL）下运行，请使用 powshell 或 cmd 都可以。
