### ISSUE TITLE
check_v2ray.py在powershell和cmd运行出问题

### ISSUE THREAD

**Issue by DawnDu** [Justsoos/ss-ssr-gadget#3]
无论是在powershell还是cmd，运行check_v2ray.py都会出现如下
`Traceback (most recent call last):`
　`File　"D:\Program Files\v2ray-v3.35-windows-64\check_v2ray.py", line 15, in <module>`
　　`import requests`
`ModuleNotFoundError: No module named 'requests'`
请问大佬，该如何解决这个问题？
![3](https://user-images.githubusercontent.com/33946525/44438823-739b6580-a5f3-11e8-8d87-81189b6e4cf9.PNG)

**Comment by Justsoos** [comment]
你的python缺少基本模块 “requests”
请 google 或者按下面教程安装模块。如果缺少其他模块，类似，用 pip install 安装：
http://docs.python-requests.org/zh_CN/latest/user/install.html
